version: '3.6'

services:
    nginx:
      image: nginx:latest
      container_name: ${PROJECT_NAME}-nginx
      restart: always
## Uncomment for nginx debug mode
#     command: [ nginx-debug, '-g', 'daemon off;' ]
      ports:
        - "${WEB_PORT_HTTP}:80"
        - "${WEB_PORT_SSL}:443"
      volumes:
        - ./application:/var/www/html:ro,cached
        - ./docker/config/dev/nginx.conf:/etc/nginx/conf.d/default.conf:ro,cached
        - ./docker/runtime/logs/nginx:/var/log/nginx
      links:
        - web
      depends_on:
        - web
      networks:
        - web

    mysql:
      image: mysql:8.0
      platform: linux/x86_64
      container_name: ${PROJECT_NAME}-mysql
      command: --innodb-use-native-aio=${INNODB_USE_NATIVE_AIO:-1} --default-authentication-plugin=mysql_native_password --sql_mode=${SQL_MODE:-"ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"}
      environment:
        MYSQL_ROOT_PASSWORD: secret
        MYSQL_DATABASE: web
      ports:
        - "33061:3306"
      volumes:
        - ./docker/runtime/db/mysql:/var/lib/mysql:delegated
        - ./docker/runtime/logs/mysql:/var/log/mysql
        - ./docker/config/${ENV}/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro,cached
      networks:
        - web

    web: &web-template
      image: ${PROJECT_NAME}-web:latest
      container_name: ${PROJECT_NAME}-web
      restart: no
      build:
        context: .
        args:
          ENV: ${ENV}
          HOST_UID: ${HOST_UID}
          HOST_GID: ${HOST_GID}
          XDEBUG_CONFIG: ${XDEBUG_CONFIG}
        dockerfile: ./docker/build/php/${ENV}.Dockerfile
      links:
        - mysql
      volumes:
        - ./application:/var/www/html
        - ./docker/config/dev/php/local.ini:/usr/local/etc/php/conf.d/zz99-local.ini
        - ./.env.${ENV}:/var/www/html/.env:ro,cached
      depends_on:
        - mysql
      networks:
        - web
      extra_hosts:
        - "host.docker.internal:host-gateway"
      working_dir: /var/www/html
      environment:
        PHP_IDE_CONFIG: "serverName=localhost"

    ### Cron tasks
#    supervisord:
#      <<: *web-template
#      container_name: ${PROJECT_NAME}-supervisord
#      expose: []
#      command: ["/usr/bin/supervisord"]

networks:
  web:
    name: ${PROJECT_NAME}-network
    driver: bridge
